//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.FleetManager.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FleetManagerDataEntities : DbContext
    {
        public FleetManagerDataEntities()
            : base("name=FleetManagerDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MstShipBase> MstShipBase { get; set; }
        public virtual DbSet<MstShipType> MstShipType { get; set; }
        public virtual DbSet<TblShipData> TblShipData { get; set; }
        public virtual DbSet<ViewAllShips> ViewAllShips { get; set; }
        public virtual DbSet<ViewNotPossessionShips> ViewNotPossessionShips { get; set; }
        public virtual DbSet<ViewPossessionShips> ViewPossessionShips { get; set; }
    }
}
