//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SO.FleetManager.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblShipData
    {
        public int ShipId { get; set; }
        public string ShipBaseCode { get; set; }
        public byte Grade { get; set; }
        public byte Level { get; set; }
        public short FirePower { get; set; }
        public short TorpedoPower { get; set; }
        public short AntiAircraft { get; set; }
        public short Armor { get; set; }
        public short Luck { get; set; }
        public short AntiSubmarine { get; set; }
        public short Avoidance { get; set; }
        public short Scouting { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
